name: Build for FreeBSD

on:
  push:
    branches:
      - "**"
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build_freebsd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64]
        include:
          - arch: x64
            rid: freebsd-x64
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Build WebUI
        run: ./webui/build.sh

      - name: Build CLI - Debug
        run: |
          dotnet publish -c Debug -r ${{ matrix.rid }} \
          /p:PublishSingleFile=true \
          /p:PublishTrimmed=true \
          BililiveRecorder.Cli/BililiveRecorder.Cli.csproj

      - name: Build CLI - Release
        run: |
          dotnet publish -c Release -r ${{ matrix.rid }} \
          /p:PublishSingleFile=true \
          /p:PublishTrimmed=true \
          BililiveRecorder.Cli/BililiveRecorder.Cli.csproj

      - name: Upload Artifacts - Debug
        uses: actions/upload-artifact@v3
        with:
          name: CLI-${{ matrix.rid }}-Debug
          path: BililiveRecorder.Cli/bin/Debug/net*/${{ matrix.rid }}/publish/
          if-no-files-found: error

      - name: Upload Artifacts - Release
        uses: actions/upload-artifact@v3
        with:
          name: CLI-${{ matrix.rid }}-Release
          path: BililiveRecorder.Cli/bin/Release/net*/${{ matrix.rid }}/publish/
          if-no-files-found: error
